repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Format code with gofumpt
      - id: go-fmt-gofumpt
        name: Format Go code
        entry: gofumpt
        language: golang
        args: [-w]
        types: [go]
        
      # Static analysis with go vet
      - id: go-vet
        name: Go vet
        entry: go
        language: system
        args: [vet, ./...]
        pass_filenames: false
        
      # Run tests
      - id: go-test
        name: Go tests
        entry: go
        language: system
        args: [test, -short, ./...]
        pass_filenames: false
        
      # Linting with golangci-lint
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint
        language: golang
        args: [run, --fix]
        types: [go]
        pass_filenames: false
        
      # Security scanning
      - id: go-sec
        name: Security scan
        entry: gosec
        language: golang
        args: [-quiet, ./...]
        pass_filenames: false
        
      # Mod tidy
      - id: go-mod-tidy
        name: Go mod tidy
        entry: go
        language: system
        args: [mod, tidy]
        pass_filenames: false
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # General file checks
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict
      
  # Commit message validation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.6.0
    hooks:
      - id: commitizen
        stages: [commit-msg]