baseURL: 'https://safurrier.github.io/go-template-project'
languageCode: 'en-us'
title: 'Go Template Project'

# Menu configuration
menu:
  main:
    - name: "Documentation"
      url: "/docs/"
      weight: 10
    - name: "API Reference" 
      url: "/api/"
      weight: 20
    - name: "Examples"
      url: "/examples/"
      weight: 30

# Markup configuration for code highlighting
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: true
    tabWidth: 4
    codeFences: true